### ISSUE TITLE
Request: Screenshot on Readme

### ISSUE THREAD

**Issue by NickLarsenNZ** [AlexImb/vue-dag#84]
This project seems interesting, but it would be nice to see a screenshot.

**Comment by AlexImb** [comment]
Thanks for your suggestion! I added some screenshots in the [README](https://github.com/AlexImb/vue-dag/blob/master/README.md) and a small demo app at: https://vue-dag-example.netlify.app

**Comment by NickLarsenNZ** [comment]
Thanks, this definitely looks cool. I'd like to use it :)
